### ISSUE TITLE
Publish.py Checks for H1 and errors if you try and publish a notebook without h1 tags

### ISSUE THREAD

**Issue by anabranch** [plotly/IPython-plotly#21]
(IPython-plotly)> make publish nb=apachespark                                                                      ~/AeroFS/Dev/IPython-plotly(master✗)@airbears2-10-142-137-24.AirBears2.1918.Berkeley.EDU
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    .../IPython-plotly/_makescripts/publish.py in <module>()
        199
        200 if __name__ == "__main__":
    --> 201     main()

    ..../IPython-plotly/_makescripts/publish.py in main()
        172
        173         # Update body
    --> 174         remove_title(body)
        175         update_anchors(body)
        176         add_lightbox(body)

    ...IPython-plotly/_makescripts/publish.py in remove_title(body)
         38 def remove_title(body):
         39     H1 = body.findAll('h1')  # TODO check 'h2' also?
    ---> 40     H1[0].extract()
         41
         42

    IndexError: list index out of range
    >.../IPython-plotly/_makescripts/publish.py(40)remove_title()
         39     H1 = body.findAll('h1')  # TODO check 'h2' also?
    ---> 40     H1[0].extract()
         41

    ipdb> ls
    *** NameError: name 'ls' is not defined
    ipdb> H1
    []
    ipdb>
    KeyboardInterrupt
    > .../IPython-plotly/_makescripts/publish.py(40)remove_title()
         39     H1 = body.findAll('h1')  # TODO check 'h2' also?
    ---> 40     H1[0].extract()
         41

**Comment by etpinard** [comment]
closed via https://github.com/plotly/IPython-plotly/commit/883007876f2e21cffb93b8a78d7b56c3a0247635
