### ISSUE TITLE
KeyError: 'Complaint Type' in Pandas Widget - Time Series, Search, and Filtering

### ISSUE THREAD

**Issue by davidlopezberzosa** [plotly/IPython-plotly#28]
Hi,

I am trying to run the "Pandas Widget - Time Series, Search, and Filtering" ipython notebook.

I get the following error: KeyError: 'Complaint Type' 

More detailed information:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-9d76d6cb05a8> in <module>()
      1 column_headers_dropdown = widgets.DropdownWidget()
      2 column_headers_dropdown.values  = {column: column for column in df.columns}
----> 3 column_headers_dropdown.value = 'Complaint Type'
      4 column_headers_dropdown.description = 'Select which column to graph (e.g. Tree)'
      5 

/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.pyc in __set__(self, obj, value)
    443             # we explicitly compare silent to True just in case the equality
    444             # comparison above returns something other than True/False
--> 445             obj._notify_trait(self.name, old_value, new_value)
    446 
    447     def _validate(self, obj, value):

/usr/local/lib/python2.7/dist-packages/IPython/html/widgets/widget.pyc in _notify_trait(self, name, old_value, new_value)
    371         # registered validation to be processed prior to allowing the widget
    372         # machinery to handle the state.
--> 373         LoggingConfigurable._notify_trait(self, name, old_value, new_value)
    374 
    375         # Send the state after the user registered callbacks for trait changes

/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.pyc in _notify_trait(self, name, old_value, new_value)
    600                     c(name, new_value)
    601                 elif nargs + offset == 3:
--> 602                     c(name, old_value, new_value)
    603                 else:
    604                     raise TraitError('a trait changed callback '

/usr/local/lib/python2.7/dist-packages/IPython/html/widgets/widget_selection.pyc in _value_changed(self, name, old, new)
    120                 # undo the change, and raise KeyError
    121                 self.value = old
--> 122                 raise KeyError(new)
    123             finally:
    124                 self.value_lock.release()

KeyError: 'Complaint Type'

Thanks a lot

**Comment by etpinard** [comment]
The notebook referred to here is not part of this repo.

Please move this issue to https://gist.github.com/chriddyp/9827cb5086cfab8da092.
