### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by etpinard** [plotly/IPython-plotly#4]
- [ ]  Update to IPython 3.0

**config**

- [ ] Handle non-pip dependencies in notebook `config.json`

- [ ] Add thumbnail image for each notebook

**make run**

- [ ] Use pip freeze (and some package) to keep track of package versions used

- [ ] Have per-notebook `requirements.txt` files

- [ ] Setup a virtualenv with those requirements

- [ ] <strike>Use `runipy` to run notebook from the command line</strike> Try IPython 3.0's nbconvert to notebook

**make publish**

- [ ] better handle `http` -> `https`

**make sync**

- [ ] add a check script to ensure that every `config.json` and `references.json` field is filled in

**Comment by mkcor** [comment]
I've been using IPython 3.0 without a problem.
