### ISSUE TITLE
Control design notebook is missing diagram image

### ISSUE THREAD

**Issue by jackparmer** [plotly/IPython-plotly#54]
![image](https://cloud.githubusercontent.com/assets/1865834/8312547/2d7b9e3a-19ab-11e5-84fe-83b7777f07ee.png)
( @moorepants )

**Comment by moorepants** [comment]
Both of the svg's are in the notebook and display when I run IPython.

I'm not sure how to check what you are seeing.

**Comment by moorepants** [comment]
How do you view locally what will be displayed on the website?

**Comment by moorepants** [comment]
I see that none of the images I have in my notebook are in `_published/static/image`. I assume that is the problem. How do you ensure they get created there?

**Comment by moorepants** [comment]
@etpinard How do I ensure the images get transferred to the correct place when running the various make targets?

**Comment by etpinard** [comment]
@moorepants my mistake. Only online images are downloaded and transferred to `_published/static/image` at the moment. 

I'm working on a fix at the moment.

**Comment by moorepants** [comment]
Ok, in the meantime, should I just manually add the svg images to that and tweak the img src urls to point to them?

**Comment by etpinard** [comment]
No need. I'm on it. The issue should be resolved in about 1 hour.

**Comment by moorepants** [comment]
Ok, thanks!
